"""done2

Revision ID: 7455ead021bf
Revises: 6990ca16931e
Create Date: 2023-08-07 13:38:46.158708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7455ead021bf'
down_revision = '6990ca16931e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
