MAX_CHARITY_PROJECT_NAME = 100
MIN_CHARITY_PROJECT_NAME_DESCRIPTION = 1
REPRESENTATION_STR_LENGTH = 20

DEFAULT_DB_URL = 'sqlite+aiosqlite:///./QRKot.db'
DEFAULT_TITLE = 'Сервис QRKot'
DEFAULT_SECRET = 'SECRET'